### PR TITLE
apollo: Add purpose annotations

### PR DESCRIPTION
**Pull request by jcharum**

### CODE REVIEW

**Review by bozhi — APPROVED** [review]

**Review by bozhi — COMMENTED** [review]
Should we add more specificity and state that it pulls enrichment data for a person? It is more than just the profile.

**Comment by jcharum** [comment]
> Should we add more specificity and state that it pulls enrichment data for a person? It is more than just the profile.

Does "enrichment" mean something to people?  I don't know much about the sort of person contemplating Apollo.  Happy to change it to whatever you think speaks to the audience.

**Comment by bozhi** [comment]
> > Should we add more specificity and state that it pulls enrichment data for a person? It is more than just the profile.
> 
> Does "enrichment" mean something to people? I don't know much about the sort of person contemplating Apollo. Happy to change it to whatever you think speaks to the audience.

I looked at the documentation again and think that we should be more specific and state something like:
"Retrieves enriched profile information of a person"


There is another API that searches for a person's profile and returns less info.

**Comment by jcharum** [comment]
I made it `Get a person's enriched profile.`:

- "Get", because I am generally standardizing on "get" for {"get","fetch","retrieve"}.
- "Get" instead of "Gets", because I am generally standardizing on imperative forms, as I think the active form sounds better and also fits better in an implied list of actions, e.g. "What actions can this integration take?  Get a person's profile; Add a row; etc.".
- "person's enriched profile" instead of "enriched profile information of a person", because I think "information" is a filler word and using the possessive makes it shorter and punchier (IMHO).

Let me know what you think!

**Comment by bozhi** [comment]
> I made it `Get a person's enriched profile.`:
> 
> * "Get", because I am generally standardizing on "get" for {"get","fetch","retrieve"}.
> * "Get" instead of "Gets", because I am generally standardizing on imperative forms, as I think the active form sounds better and also fits better in an implied list of actions, e.g. "What actions can this integration take?  Get a person's profile; Add a row; etc.".
> * "person's enriched profile" instead of "enriched profile information of a person", because I think "information" is a filler word and using the possessive makes it shorter and punchier (IMHO).
> 
> Let me know what you think!

Looks good.

**Comment by jcharum** [comment]
@bozhi: Re-import?  Thanks!!!

**Pull request merged**
